export default [
    // canvas no-0
    [
        {
            startIndex: 0,
            numImages: 150,
            duration: 3,
            size: 188,
            top: 26,
            left: 17,
            zIndex: 0,
        },
        {
            startIndex: 150,
            numImages: 150,
            duration: 3,
            size: 221,
            top: 55,
            left: 50,
            zIndex: 2,
        },
        {
            startIndex: 300,
            numImages: 150,
            duration: 3,
            size: 160,
            top: 10,
            left: 80,
            zIndex: 0,
        },
        {
            startIndex: 450,
            numImages: 150,
            duration: 3,
            size: 137,
            top: 2,
            left: 40,
            zIndex: 0,
        },
        {
            startIndex: 600,
            numImages: 150,
            duration: 3,
            size: 249,
            top: 19,
            left: 60,
            zIndex: 0,
        },
        {
            startIndex: 750,
            numImages: 150,
            duration: 3,
            size: 205,
            top: 10,
            left: 2,
            zIndex: 0,
        },
        {
            startIndex: 900,
            numImages: 150,
            duration: 3,
            size: 158,
            top: 74,
            left: 11,
            zIndex: 0,
        },
    ],
    // canvas no-1
    [
        {
            startIndex: 0,
            numImages: 150,
            duration: 3,
            size: 162,
            top: 20,
            left: 11,
            zIndex: 0,
        },
        {
            startIndex: 150,
            numImages: 150,
            duration: 3,
            size: 97,
            top: 7,
            left: 64,
            zIndex: 0,
        },
        {
            startIndex: 300,
            numImages: 150,
            duration: 3,
            size: 197,
            top: 70,
            left: 56,
            zIndex: 0,
        },
        {
            startIndex: 450,
            numImages: 150,
            duration: 3,
            size: 162,
            top: 72,
            left: 11,
            zIndex: 0,
        },
        {
            startIndex: 600,
            numImages: 150,
            duration: 3,
            size: 102,
            top: 12,
            left: 84,
            zIndex: 2,
        },
        {
            startIndex: 750,
            numImages: 150,
            duration: 3,
            size: 197,
            top: 20,
            left: 56,
            zIndex: 0,
        },
    ],
    // canvas no-2
    [
        {
            startIndex: 0,
            numImages: 150,
            duration: 3,
            size: 230,
            top: 52,
            left: 3,
            zIndex: 0,
        },
        {
            startIndex: 150,
            numImages: 150,
            duration: 3,
            size: 101,
            top: 21,
            left: 47,
            zIndex: 0,
        },
        {
            startIndex: 300,
            numImages: 150,
            duration: 3,
            size: 116,
            top: 31,
            left: 69,
            zIndex: 0,
        },
    ],
    // canvas no-3
    [
        {
            startIndex: 0,
            numImages: 150,
            duration: 3,
            size: 198,
            top: 63,
            left: 29,
            zIndex: 0,
        },
        {
            startIndex: 150,
            numImages: 150,
            duration: 3,
            size: 277,
            top: 8,
            left: 56,
            zIndex: 0,
        },
        {
            startIndex: 300,
            numImages: 150,
            duration: 3,
            size: 292,
            top: 36,
            left: 20,
            zIndex: 0,
        },
        {
            startIndex: 450,
            numImages: 150,
            duration: 3,
            size: 100,
            top: 5,
            left: 10,
            zIndex: 2,
        },
        {
            startIndex: 600,
            numImages: 150,
            duration: 3,
            size: 156,
            top: 73,
            left: 40,
            zIndex: 0,
        },
    ],
    // canvas no-4
    [
        {
            startIndex: 0,
            numImages: 150,
            duration: 3,
            size: 121,
            top: 58,
            left: 14,
            zIndex: 0,
        },
        {
            startIndex: 150,
            numImages: 150,
            duration: 3,
            size: 256,
            top: 33,
            left: 50,
            zIndex: 0,
        },
        {
            startIndex: 300,
            numImages: 150,
            duration: 3,
            size: 174,
            top: 7,
            left: 19,
            zIndex: 0,
        },
    ],
    // canvas no-5
    [
        {
            startIndex: 0,
            numImages: 150,
            duration: 3,
            size: 140,
            top: 75,
            left: 31,
            zIndex: 0,
        },
        {
            startIndex: 150,
            numImages: 150,
            duration: 3,
            size: 158,
            top: 61,
            left: 64,
            zIndex: 0,
        },
        {
            startIndex: 300,
            numImages: 150,
            duration: 3,
            size: 240,
            top: 33,
            left: 14,
            zIndex: 2,
        },
    ],
    // canvas no-6
    [
        {
            startIndex: 0,
            numImages: 150,
            duration: 3,
            size: 157,
            top: 5,
            left: 14,
            zIndex: 0,
        },
        {
            startIndex: 150,
            numImages: 150,
            duration: 3,
            size: 227,
            top: 10,
            left: 48,
            zIndex: 0,
        },
        {
            startIndex: 300,
            numImages: 150,
            duration: 3,
            size: 273,
            top: 63,
            left: 10,
            zIndex: 0,
        },
    ],
    // canvas no-7
    [
        {
            startIndex: 0,
            numImages: 150,
            duration: 3,
            size: 194,
            top: 79,
            left: 50,
            zIndex: 0,
        },
        {
            startIndex: 150,
            numImages: 150,
            duration: 3,
            size: 166,
            top: 29,
            left: 18,
            zIndex: 0,
        },
        {
            startIndex: 300,
            numImages: 150,
            duration: 3,
            size: 192,
            top: 52,
            left: 17,
            zIndex: 0,
        },
        {
            startIndex: 450,
            numImages: 150,
            duration: 3,
            size: 132,
            top: 13,
            left: 39,
            zIndex: 2,
        },
        {
            startIndex: 600,
            numImages: 150,
            duration: 3,
            size: 190,
            top: 25,
            left: 68,
            zIndex: 0,
        },
        {
            startIndex: 750,
            numImages: 150,
            duration: 3,
            size: 237,
            top: 35,
            left: 63,
            zIndex: 0,
        },
    ],
    // canvas no-8
    [
        {
            startIndex: 0,
            numImages: 150,
            duration: 3,
            size: 174,
            top: 86,
            left: 18,
            zIndex: 0,
        },
        {
            startIndex: 150,
            numImages: 150,
            duration: 3,
            size: 150,
            top: 88,
            left: 78,
            zIndex: 0,
        },
        {
            startIndex: 300,
            numImages: 150,
            duration: 3,
            size: 176,
            top: 80,
            left: 32,
            zIndex: 2,
        },
    ],
    // canvas no-9
    [
        {
            startIndex: 0,
            numImages: 150,
            duration: 3,
            size: 250,
            top: -10,
            left: 30,
            zIndex: 0,
        },
        {
            startIndex: 150,
            numImages: 150,
            duration: 3,
            size: 163,
            top: 10,
            left: 64,
            zIndex: 0,
        },
        {
            startIndex: 300,
            numImages: 150,
            duration: 3,
            size: 144,
            top: 13,
            left: 12,
            zIndex: 0,
        },
        // {
        //     startIndex: 450,
        //     numImages: 150,
        //     duration: 3,
        //     size: 208,
        //     top: 13,
        //     left: 8,
        //     zIndex: 0,
        // },
    ],
]